### ISSUE TITLE
Reflecting on a class with a property that is readonly (get accessor only, no set) throws System.NullReferenceException

### ISSUE THREAD

**Issue by raxuser100** [replaysMike/TypeSupport#22]
It seems that when reflecting on a `Class`, if a `Property `has only the get accessor, then an exception is thrown. 

```
using System.Linq;
using CCTools.Diagnostics;
using CCTools.UnitTestHelpers.XUnit.Common;
using TypeSupport;
using TypeSupport.Extensions;
using Xunit;
using Xunit.Abstractions;
namespace CCTools.DevIdeas.UnitTest.Reflection
{
    public class Cat
    {
        public string Name { get; } = "Sarah";
        public int Age { get; set; } = 6;
    }

    public class Test_Reflection_Helpers_Review : TestWithLoggerBase
    {
        /// <inheritdoc />
        public Test_Reflection_Helpers_Review(ITestOutputHelper logger) : base(logger) { }

        [Fact]
        public void Test_playground_for_TypeSupport_nuget_package()
        {
            //Cat c = (Cat) SimpleTestClassesHelper.CatCreate(1);

            Cat c = new Cat();
            ExtendedType tx = c.GetType().GetExtendedType();
            Logger.WriteLine(tx.IsInterface.ToString());
            Logger.WriteLine(DebugHelper.FormatListInTableStyle(tx.Properties.Select(i => i.Name)));

            foreach (ExtendedProperty p in tx.Properties) Logger.WriteLine(p.Name);
            //Logger.WriteLine(DebugHelper.FormatListInTableStyle(tx.Properties.Select(i=> i.Name)));
        }
    }
}
```
Throws the following error:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at TypeSupport.Extensions.TypeExtensions.<>c.<GetProperties>b__0_0(PropertyInfo x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by replaysMike** [comment]
Closing this issue as it could not be reproduced, perhaps this was fixed in a later version. Test added to confirm this works.
